# Generated by Django 4.0.4 on 2022-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0002_remove_ads_updated_by_remove_ads_updated_dt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
