# Generated by Django 4.0.4 on 2022-04-28 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdsBoard', '0003_ads_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ads',
            name='updated_dt',
            field=models.DateTimeField(null=True),
        ),
    ]
