# Generated by Django 4.0.4 on 2022-04-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0003_ads_updated_by_ads_updated_dt'),
        ('AdsBoard', '0004_ads_updated_by_ads_updated_dt'),
    ]

    operations = [
    ]
