# Generated by Django 4.0.4 on 2022-04-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0004_ads_updated_by_ads_updated_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='messageAds',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
