# Generated by Django 4.0.4 on 2022-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0006_ads_messageads'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
