# Generated by Django 4.0.4 on 2022-05-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0008_ads_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='img',
            field=models.ImageField(null=True, upload_to='static/imgAds/%y/%m/%d'),
        ),
    ]
