# Generated by Django 4.0.4 on 2022-05-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0009_ads_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/imgAds/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='section',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
