# Generated by Django 4.0.4 on 2022-05-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0005_ads_messageads'),
        ('AdsBoard', '0013_alter_ads_messageads'),
    ]

    operations = [
    ]
