# Generated by Django 4.0.4 on 2022-05-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0015_alter_ads_messageads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='messageAds',
            field=models.TextField(max_length=4000, null=True),
        ),
    ]
