# Generated by Django 4.0.4 on 2022-05-16 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0019_ads_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='save_by',
        ),
        migrations.RemoveField(
            model_name='archives',
            name='save_dt',
        ),
    ]
