# Generated by Django 4.0.4 on 2022-05-16 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0020_remove_archives_save_by_remove_archives_save_dt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archives',
        ),
    ]
