# Generated by Django 4.0.4 on 2022-05-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdsBoard', '0021_delete_archives'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save_dt', models.DateTimeField(auto_now_add=True)),
                ('ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='AdsBoard.ads')),
                ('save_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
