# Generated by Django 4.0.4 on 2022-05-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0022_archives'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='ads',
        ),
        migrations.AddField(
            model_name='archives',
            name='ads',
            field=models.ManyToManyField(related_name='archive', to='AdsBoard.ads'),
        ),
    ]
