# Generated by Django 4.0.4 on 2022-05-19 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0024_remove_archives_ads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archives',
            name='save_by',
        ),
    ]
