# Generated by Django 4.0.4 on 2022-05-19 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdsBoard', '0026_archives_ads_archives_save_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='ads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='AdsBoard.ads'),
        ),
        migrations.AlterField(
            model_name='archives',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to=settings.AUTH_USER_MODEL),
        ),
    ]
