# Generated by Django 4.0.4 on 2022-05-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0028_alter_archives_ads'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='description_ar',
            field=models.CharField(default='section', max_length=150),
        ),
        migrations.AddField(
            model_name='section',
            name='name_ar',
            field=models.CharField(default='section', max_length=50),
        ),
    ]
