# Generated by Django 4.0.4 on 2022-05-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='bio', max_length=100),
        ),
    ]
