# Generated by Django 4.0.4 on 2022-05-29 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0031_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AdsBoard.profile'),
        ),
    ]
