# Generated by Django 4.0.4 on 2022-05-29 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0032_alter_comments_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='save_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archive', to='AdsBoard.profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AdsBoard.profile'),
        ),
    ]
