# Generated by Django 4.0.4 on 2022-05-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0033_alter_archives_save_by_alter_comments_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='AdsBoard.profile'),
        ),
    ]
