# Generated by Django 4.0.4 on 2022-05-29 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0034_alter_ads_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='AdsBoard.profile'),
        ),
    ]
