# Generated by Django 4.0.4 on 2022-06-01 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdsBoard', '0039_alter_profile_gender_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='section', max_length=150),
        ),
    ]
