from django.urls import path
from . import views
urlpatterns = [
    path('',views.home,name='home'),
    # path('',views.SectionListView.as_view(),name='home'),
    path('users/<int:user_type>',views.listuser,name='listuser'),
    path('users/<int:user_id>/edit', views.usersEditView.as_view(), name='usersEditView'),
    path('waitingAds/',views.waitingAds,name='waitingAds'),
    # path('EditeUser/', views.EditeUser, name='EditeUser'),
    # path('profile/ddd/<int:user_id>', views.update_Profile_view, name='update_Profile_view'),

    path('ArchivesAds/',views.ArchivesAds,name='ArchivesAds'),
    path('UserProfile/<int:user_id>',views.UserProfile,name='UserProfile'),
    path('Section/Ads/<int:ads_id>/save/<int:id>', views.saveArchivesAds, name='saveArchivesAds'),
    path('Section/Ads/<int:ads_id>/delete/<int:id>', views.deleteArchivesAds, name='deleteArchivesAds'),
    path('Section/waitingAds/<int:ads_id>/Accept/',views.Accept,name='Accept'),
    path('Section/waitingAds/<int:ads_id>/Rejection/',views.Rejection,name='Rejection'),
    path('Section/<int:section_id>/BandUserAds/<int:user_id>/band/<int:id>',views.BandUserAds,name='BandUserAds'),
    path('Section/<int:section_id>/',views.SectionAds,name='SectionAds'),
    path('Section/<int:section_id>/Search',views.SectionAdsSearch,name='SectionAdsSearch'),
    path('Section/<int:section_id>/edit',views.SectionEditView.as_view(),name='SectionEditView'),
    path('Section/<int:section_id>/new/',views.newAds,name='newAds'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/DeleteAds/<int:id>',views.DeleteAds,name='DeleteAds'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/comment/<int:id>/',views.adsComments,name='adsComments'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/reply/<int:id>',views.replyAds,name='replyAds'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/edit/<int:id>',views.AdsUpdateView.as_view(),name='AdsUpdateView'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/comment/<int:comment_id>/edit//<int:id>',views.CommentUpdateView.as_view(),name='CommentUpdateView'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/comment/<int:comment_id>/Delete//<int:id>',views.CommentDelete,name='CommentDelete'),
    path('Section/<int:section_id>/Ads/<int:ads_id>/comment/<int:user_id>/BandUserComment//<int:id>',views.BandUserComment,name='BandUserComment'),
]
